# Generated by Django 4.0.4 on 2022-05-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_charge_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
